USE [master]
GO

/****** Object:  Database [sale_website]    Script Date: 04/07/2025 11:24:52 CH ******/
DROP DATABASE [sale_website]
GO

/****** Object:  Database [sale_website]    Script Date: 04/07/2025 11:24:52 CH ******/
CREATE DATABASE [sale_website]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sale_website', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\sale_website.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sale_website_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\sale_website_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sale_website].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sale_website] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sale_website] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sale_website] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sale_website] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sale_website] SET ARITHABORT OFF 
GO

ALTER DATABASE [sale_website] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sale_website] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sale_website] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sale_website] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sale_website] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sale_website] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sale_website] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sale_website] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sale_website] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sale_website] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sale_website] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sale_website] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sale_website] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sale_website] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sale_website] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sale_website] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sale_website] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sale_website] SET RECOVERY FULL 
GO

ALTER DATABASE [sale_website] SET  MULTI_USER 
GO

ALTER DATABASE [sale_website] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sale_website] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sale_website] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sale_website] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sale_website] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sale_website] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sale_website] SET QUERY_STORE = ON
GO

ALTER DATABASE [sale_website] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [sale_website] SET  READ_WRITE 
GO


